apiVersion: 1

datasources:
  - name: AutoTrader API
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    jsonData:
      # Base URL for Grafana Infinity plugin
      url: http://localhost:3001
    editable: true
